# Generated by Django 4.0.6 on 2022-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
